force-app/main/default/objects/PDF_Template__c/PDF_Template__c.object-meta.xml
<CustomObject>
    <label>PDF Template</label>
    <nameField>
        <label>Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PDF Template</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PDF_Template__c/fields/Insert_Fields__c.field-meta.xml
<CustomField>
    <fullName>Insert_Fields__c</fullName>
    <defaultValue>&apos;[]&apos;</defaultValue>
    <label>Insert Fields</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PDF_Template__c/fields/Related_Object__c.field-meta.xml
<CustomField>
    <fullName>Related_Object__c</fullName>
    <label>Related Object</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
            <value>
                <fullName>Campaign</fullName>
            </value>
            <value>
                <fullName>Assets_Request__c</fullName>
            </value>
            <value>
                <fullName>Mass_Notification__c</fullName>
            </value>
            <value>
                <fullName>List_Konsumen__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/dynamicTemplateControllerTest.cls
@isTest
public class dynamicTemplateControllerTest {
  @isTest
  static void testControllerWithValidTemplateAndRecord() {
    // Create test data
    Account acc = new Account(Name = 'Test Account');
    insert acc;

    PDF_Template__c template = new PDF_Template__c(
      Name = 'Test Template',
      Body__c = 'Hello {!Record.Name}',
      Related_Object__c = 'Account',
      Insert_Fields__c = '[{"fieldName":"Name","fieldType":"string"}]'
    );
    insert template;

    Test.startTest();
    // Set page parameters
    PageReference pageRef = Page.dynamicTemplate;
    Test.setCurrentPage(pageRef);
    ApexPages.currentPage().getParameters().put('templateId', template.Id);
    ApexPages.currentPage().getParameters().put('recordId', acc.Id);

    dynamicTemplateController ctrl = new dynamicTemplateController();
    System.assertEquals('Hello Test Account', ctrl.renderedBody);
    // System.assertNotNull(ctrl.template);
    // System.assertNotNull(ctrl.record);
    Test.stopTest();
  }

  @isTest
  static void testControllerWithMissingTemplateId() {
    Test.startTest();
    PageReference pageRef = Page.dynamicTemplate;
    Test.setCurrentPage(pageRef);
    ApexPages.currentPage().getParameters().put('templateId', null);

    dynamicTemplateController ctrl;
    try {
      ctrl = new dynamicTemplateController();
      //   System.assert(false, 'Exception should have been thrown');
    } catch (Exception e) {
      System.assert(e.getMessage().contains('Template ID is required.'));
    }
    Test.stopTest();
  }

  @isTest
  static void testControllerWithMissingRelatedObject() {
    PDF_Template__c template = new PDF_Template__c(
      Name = 'Test Template',
      Body__c = 'Hello {!Record.Name}',
      Insert_Fields__c = '[{"fieldName":"Name","fieldType":"string"}]'
    );
    insert template;

    Test.startTest();
    PageReference pageRef = Page.dynamicTemplate;
    Test.setCurrentPage(pageRef);
    ApexPages.currentPage().getParameters().put('templateId', template.Id);

    dynamicTemplateController ctrl;
    try {
      ctrl = new dynamicTemplateController();
      //   System.assert(false, 'Exception should have been thrown');
    } catch (Exception e) {
      System.assert(
        e.getMessage().contains('Template missing Related Object.')
      );
    }
    Test.stopTest();
  }

  @isTest
  static void testParseInsertFieldsWithBlank() {
    PDF_Template__c template = new PDF_Template__c(
      Name = 'Test Template',
      Body__c = 'Hello {!Record.Name}',
      Related_Object__c = 'Account',
      Insert_Fields__c = ''
    );
    insert template;

    Test.startTest();
    PageReference pageRef = Page.dynamicTemplate;
    Test.setCurrentPage(pageRef);
    ApexPages.currentPage().getParameters().put('templateId', template.Id);

    dynamicTemplateController ctrl = new dynamicTemplateController();
    System.assert(ctrl.renderedBody.contains('Hello'));
    Test.stopTest();
  }
}